// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxMjKPHHd8-3Vv5A_sQFvanscB3l2Jf04',
    appId: '1:607917888128:web:0e8ca06718133cda290c65',
    messagingSenderId: '607917888128',
    projectId: 'hacka-e33f3',
    authDomain: 'hacka-e33f3.firebaseapp.com',
    storageBucket: 'hacka-e33f3.appspot.com',
    measurementId: 'G-4QSQFP3GYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOh0_cfR9Nj2l-5s6uC55D5uOIoHE3lpA',
    appId: '1:607917888128:android:0fbc17c63a5d85d1290c65',
    messagingSenderId: '607917888128',
    projectId: 'hacka-e33f3',
    storageBucket: 'hacka-e33f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ysdmd00om4lUh8hX-etCiOTZ5Xhkq-g',
    appId: '1:607917888128:ios:4496b8412fc137e8290c65',
    messagingSenderId: '607917888128',
    projectId: 'hacka-e33f3',
    storageBucket: 'hacka-e33f3.appspot.com',
    iosBundleId: 'com.example.hacka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ysdmd00om4lUh8hX-etCiOTZ5Xhkq-g',
    appId: '1:607917888128:ios:e14188802ad47c60290c65',
    messagingSenderId: '607917888128',
    projectId: 'hacka-e33f3',
    storageBucket: 'hacka-e33f3.appspot.com',
    iosBundleId: 'com.example.hacka.RunnerTests',
  );
}
